// projects.js
// 100 Project Ideas - Language aur Level ke hisaab se

const projects = [

    // ===================== PYTHON =====================

    { id: 1, title: "Calculator", level: "Basic", language: "Python", description: "A simple calculator for basic arithmetic operations." },
    { id: 2, title: "Number Guessing Game", level: "Basic", language: "Python", description: "A game where the user tries to guess a randomly generated number." },
    { id: 3, title: "To-Do List (CLI)", level: "Basic", language: "Python", description: "A command-line app to add, view and remove daily tasks." },
    { id: 4, title: "Unit Converter", level: "Basic", language: "Python", description: "Convert between units like km-miles, kg-lbs, Celsius-Fahrenheit." },
    { id: 5, title: "Simple Quiz App", level: "Basic", language: "Python", description: "Ask the user multiple-choice questions and show a final score." },
    { id: 6, title: "BMI Calculator", level: "Basic", language: "Python", description: "Calculate Body Mass Index from height and weight input." },
    { id: 7, title: "Password Generator", level: "Basic", language: "Python", description: "Generate strong random passwords of a given length." },
    { id: 8, title: "Rock Paper Scissors Game", level: "Basic", language: "Python", description: "Classic game where the user plays against the computer." },
    { id: 9, title: "Temperature Converter", level: "Basic", language: "Python", description: "Convert temperature between Celsius, Fahrenheit and Kelvin." },
    { id: 10, title: "Student Management System", level: "Medium", language: "Python", description: "Add, update, delete and search student records." },
    { id: 11, title: "Library Management System", level: "Medium", language: "Python", description: "Track books, members, and issue/return dates." },
    { id: 12, title: "Contact Book App", level: "Medium", language: "Python", description: "Save and search contacts with name, phone and email." },
    { id: 13, title: "Expense Tracker", level: "Medium", language: "Python", description: "Log daily expenses and view monthly spending summaries." },
    { id: 14, title: "Weather App", level: "Medium", language: "Python", description: "Fetch and display live weather data using a public API." },
    { id: 15, title: "Tic Tac Toe Game", level: "Medium", language: "Python", description: "Two-player Tic Tac Toe with win/draw detection." },
    { id: 16, title: "URL Shortener", level: "Medium", language: "Python", description: "Convert long URLs into short, shareable links." },
    { id: 17, title: "Simple Web Scraper", level: "Medium", language: "Python", description: "Extract data like prices or headlines from a webpage." },
    { id: 18, title: "Text-Based Adventure Game", level: "Medium", language: "Python", description: "A story-driven game where choices affect the outcome." },
    { id: 19, title: "AI Chatbot", level: "Advanced", language: "Python", description: "A chatbot that understands and responds to user questions." },
    { id: 20, title: "Movie Recommendation System", level: "Advanced", language: "Python", description: "Suggest movies based on user preferences using similarity scores." },
    { id: 21, title: "Face Detection App", level: "Advanced", language: "Python", description: "Detect faces in images or webcam feed using OpenCV." },
    { id: 22, title: "Spam Email Classifier", level: "Advanced", language: "Python", description: "Classify emails as spam or not using machine learning." },
    { id: 23, title: "Stock Price Predictor", level: "Advanced", language: "Python", description: "Predict future stock trends using historical data." },
    { id: 24, title: "Voice Assistant", level: "Advanced", language: "Python", description: "A Jarvis-style assistant that responds to voice commands." },
    { id: 25, title: "Handwritten Digit Recognizer", level: "Advanced", language: "Python", description: "Recognize handwritten digits using a neural network." },

    // ===================== JAVA =====================

    { id: 26, title: "Calculator", level: "Basic", language: "Java", description: "A console-based calculator for basic operations." },
    { id: 27, title: "Simple Banking System", level: "Basic", language: "Java", description: "Deposit, withdraw and check balance for a single account." },
    { id: 28, title: "Number Palindrome Checker", level: "Basic", language: "Java", description: "Check if a given number or string is a palindrome." },
    { id: 29, title: "Student Grade Calculator", level: "Basic", language: "Java", description: "Calculate grades and percentage from subject marks." },
    { id: 30, title: "Basic Calendar App", level: "Basic", language: "Java", description: "Display a calendar for any given month and year." },
    { id: 31, title: "Simple Quiz Game", level: "Basic", language: "Java", description: "A console quiz game with score tracking." },
    { id: 32, title: "Temperature Converter", level: "Basic", language: "Java", description: "Convert temperatures between different scales." },
    { id: 33, title: "Currency Converter", level: "Basic", language: "Java", description: "Convert amounts between currencies using fixed rates." },
    { id: 34, title: "Basic Chat Application", level: "Basic", language: "Java", description: "A simple console-based two-user chat simulation." },
    { id: 35, title: "Student Management System", level: "Medium", language: "Java", description: "Manage student records with add, update and delete features." },
    { id: 36, title: "Library Management System", level: "Medium", language: "Java", description: "Manage books, members and borrowing records." },
    { id: 37, title: "Employee Management System", level: "Medium", language: "Java", description: "Store and manage employee details and salaries." },
    { id: 38, title: "Hotel Reservation System", level: "Medium", language: "Java", description: "Book, cancel and view hotel room reservations." },
    { id: 39, title: "Inventory Management System", level: "Medium", language: "Java", description: "Track stock levels, purchases and sales of items." },
    { id: 40, title: "Online Quiz System", level: "Medium", language: "Java", description: "A quiz system with categories, timer and scoring." },
    { id: 41, title: "Railway Reservation System", level: "Medium", language: "Java", description: "Book train tickets and manage seat availability." },
    { id: 42, title: "ATM Simulation", level: "Medium", language: "Java", description: "Simulate ATM operations like withdraw, deposit and mini statement." },
    { id: 43, title: "E-commerce Cart System", level: "Medium", language: "Java", description: "Add products to a cart and calculate the total bill." },
    { id: 44, title: "Chat Application (Sockets)", level: "Advanced", language: "Java", description: "Real-time chat between multiple clients using socket programming." },
    { id: 45, title: "Multiplayer Tic Tac Toe", level: "Advanced", language: "Java", description: "Two players connect over a network and play Tic Tac Toe." },
    { id: 46, title: "Mini Compiler/Interpreter", level: "Advanced", language: "Java", description: "Build a simple interpreter for a small custom language." },
    { id: 47, title: "Bank Management System (DB)", level: "Advanced", language: "Java", description: "A full banking app connected to a real database." },
    { id: 48, title: "Job Portal Application", level: "Advanced", language: "Java", description: "A platform where employers post jobs and users apply." },
    { id: 49, title: "E-Learning Platform Backend", level: "Advanced", language: "Java", description: "Backend for courses, enrollments and progress tracking." },
    { id: 50, title: "Hospital Management System", level: "Advanced", language: "Java", description: "Manage patients, doctors, appointments and billing." },

    // ===================== C++ =====================

    { id: 51, title: "Calculator", level: "Basic", language: "C++", description: "A console calculator supporting basic arithmetic." },
    { id: 52, title: "Simple Banking System", level: "Basic", language: "C++", description: "Basic deposit, withdraw and balance check program." },
    { id: 53, title: "Student Record System", level: "Basic", language: "C++", description: "Store and display student records using structures/arrays." },
    { id: 54, title: "Number Pattern Programs", level: "Basic", language: "C++", description: "Print number, star and pyramid patterns using loops." },
    { id: 55, title: "Matrix Operations", level: "Basic", language: "C++", description: "Add, subtract and multiply matrices." },
    { id: 56, title: "Simple Library System", level: "Basic", language: "C++", description: "Add, search and remove books from a small library list." },
    { id: 57, title: "Tic Tac Toe Game", level: "Basic", language: "C++", description: "Console-based two-player Tic Tac Toe." },
    { id: 58, title: "Temperature Converter", level: "Basic", language: "C++", description: "Convert temperature values between scales." },
    { id: 59, title: "Basic Inventory System", level: "Basic", language: "C++", description: "Track item quantities and prices in a small shop." },
    { id: 60, title: "Hospital Management System", level: "Medium", language: "C++", description: "Manage patient records, doctors and appointments." },
    { id: 61, title: "Airline Reservation System", level: "Medium", language: "C++", description: "Book and cancel flight tickets with seat tracking." },
    { id: 62, title: "Snake Game (Console)", level: "Medium", language: "C++", description: "The classic Snake game rendered in the console." },
    { id: 63, title: "File-based Employee Management", level: "Medium", language: "C++", description: "Store employee data persistently using file handling." },
    { id: 64, title: "Data Structures Visualizer", level: "Medium", language: "C++", description: "Visualize stack, queue and linked list operations step by step." },
    { id: 65, title: "Simple Chess Game (Console)", level: "Medium", language: "C++", description: "A basic two-player chess game with move validation." },
    { id: 66, title: "Contact Management System", level: "Medium", language: "C++", description: "Store, search and update contact details." },
    { id: 67, title: "Hotel Management System", level: "Medium", language: "C++", description: "Manage room bookings, billing and guest details." },
    { id: 68, title: "Parking Management System", level: "Medium", language: "C++", description: "Track available slots and manage vehicle entry/exit." },
    { id: 69, title: "Custom Memory Allocator", level: "Advanced", language: "C++", description: "Implement your own malloc/free style memory manager." },
    { id: 70, title: "Mini OS Simulation", level: "Advanced", language: "C++", description: "Simulate CPU scheduling and memory management algorithms." },
    { id: 71, title: "Simple Compiler/Interpreter", level: "Advanced", language: "C++", description: "Build lexer, parser and evaluator for a mini language." },
    { id: 72, title: "Pathfinding Visualizer", level: "Advanced", language: "C++", description: "Visualize graph algorithms like BFS, DFS and A*." },
    { id: 73, title: "Multi-threaded Chat Server", level: "Advanced", language: "C++", description: "A chat server handling multiple clients using threads." },
    { id: 74, title: "Simple Database Engine", level: "Advanced", language: "C++", description: "Build a basic engine supporting insert, query and delete." },
    { id: 75, title: "Encryption/Decryption Tool", level: "Advanced", language: "C++", description: "Implement classic ciphers or basic cryptography algorithms." },

    // ===================== JAVASCRIPT =====================

    { id: 76, title: "Calculator (Web)", level: "Basic", language: "JavaScript", description: "A browser-based calculator with a clickable UI." },
    { id: 77, title: "To-Do List App", level: "Basic", language: "JavaScript", description: "Add, complete and delete tasks in the browser." },
    { id: 78, title: "Digital Clock", level: "Basic", language: "JavaScript", description: "A live-updating digital clock on a webpage." },
    { id: 79, title: "Random Quote Generator", level: "Basic", language: "JavaScript", description: "Show a new random quote every time a button is clicked." },
    { id: 80, title: "Simple Calculator with UI", level: "Basic", language: "JavaScript", description: "A styled calculator using HTML, CSS and JavaScript." },
    { id: 81, title: "Color Picker Tool", level: "Basic", language: "JavaScript", description: "Pick a color and display its HEX/RGB values." },
    { id: 82, title: "BMI Calculator (Web)", level: "Basic", language: "JavaScript", description: "A web form to calculate and display BMI results." },
    { id: 83, title: "Countdown Timer", level: "Basic", language: "JavaScript", description: "Set a target date/time and count down to it." },
    { id: 84, title: "Image Slider", level: "Basic", language: "JavaScript", description: "An automatic/manual image carousel/slider." },
    { id: 85, title: "Weather App (API)", level: "Medium", language: "JavaScript", description: "Fetch live weather data from an API and display it nicely." },
    { id: 86, title: "Expense Tracker (Web)", level: "Medium", language: "JavaScript", description: "Track income and expenses with charts using LocalStorage." },
    { id: 87, title: "Movie Search App", level: "Medium", language: "JavaScript", description: "Search and display movie details using a public API." },
    { id: 88, title: "Chat Application (Socket.io)", level: "Medium", language: "JavaScript", description: "A real-time chat app using Node.js and Socket.io." },
    { id: 89, title: "Quiz App (Web)", level: "Medium", language: "JavaScript", description: "An interactive quiz with a timer and scoring system." },
    { id: 90, title: "Recipe Finder App", level: "Medium", language: "JavaScript", description: "Search recipes by ingredient using a food API." },
    { id: 91, title: "Notes App (LocalStorage)", level: "Medium", language: "JavaScript", description: "Create and save notes that persist using LocalStorage." },
    { id: 92, title: "E-commerce Product Page", level: "Medium", language: "JavaScript", description: "A product listing page with cart and filter functionality." },
    { id: 93, title: "Portfolio Website", level: "Medium", language: "JavaScript", description: "A personal portfolio site with animations and interactivity." },
    { id: 94, title: "Real-time Chat App (Node.js)", level: "Advanced", language: "JavaScript", description: "A full-stack real-time chat app with rooms and typing indicators." },
    { id: 95, title: "Full-stack Blog Platform", level: "Advanced", language: "JavaScript", description: "A blog platform with authentication, posts and comments." },
    { id: 96, title: "Video Call App (WebRTC)", level: "Advanced", language: "JavaScript", description: "A peer-to-peer video calling app using WebRTC." },
    { id: 97, title: "AI-powered Resume Builder", level: "Advanced", language: "JavaScript", description: "Generate resume content suggestions using an AI API." },
    { id: 98, title: "Kanban Board (Drag & Drop)", level: "Advanced", language: "JavaScript", description: "A Trello-style task board with drag-and-drop columns." },
    { id: 99, title: "E-commerce Full Stack App", level: "Advanced", language: "JavaScript", description: "A complete store with products, cart, checkout and orders." },
    { id: 100, title: "Real-time Collaborative Code Editor", level: "Advanced", language: "JavaScript", description: "Multiple users editing the same code file live, like Google Docs." }

];